"""
Role-based presets for engineering and data/AI disciplines.
"""

from typing import Any

PRESETS: dict[str, dict[str, Any]] = {
    "backend": {
        "title": "Backend & Distributed Systems",
        "subtitle": "Scalable Microservices • High-Throughput Pipelines • Cloud Architecture",
        "icons": [
            ("Golang", "assets/backend/golang.svg"),
            ("Java", "assets/backend/java.svg"),
            ("Python", "assets/backend/python.svg"),
            ("Kubernetes", "assets/cloud-devops/kubernetes.svg"),
            ("Kafka", "assets/messaging/kafka.svg"),
            ("Redis", "assets/databases/redis.svg"),
            ("PostgreSQL", "assets/databases/postgresql.svg"),
            ("AWS", "assets/cloud-devops/aws.svg"),
        ],
    },
    "fullstack": {
        "title": "Full-Stack Software Engineer",
        "subtitle": "Modern Web Applications • Type-Safe Systems • Cloud Native",
        "icons": [
            ("TypeScript", "assets/frontend/typescript.svg"),
            ("React", "assets/frontend/react.svg"),
            ("Next.js", "assets/frontend/nextjs.svg"),
            ("Node.js", "assets/backend/nodejs.svg"),
            ("Tailwind CSS", "assets/frontend/tailwindcss.svg"),
            ("PostgreSQL", "assets/databases/postgresql.svg"),
            ("Docker", "assets/cloud-devops/docker.svg"),
            ("AWS", "assets/cloud-devops/aws.svg"),
        ],
    },
    "ai_ml": {
        "title": "AI & Machine Learning Engineer",
        "subtitle": "Deep Learning • LLM Pipelines • MLOps & Distributed Training",
        "icons": [
            ("Python", "assets/backend/python.svg"),
            ("PyTorch", "assets/ai-ml/pytorch.svg"),
            ("JAX", "assets/ai-ml/jax.svg"),
            ("Hugging Face", "assets/ai-ml/huggingface.svg"),
            ("LangChain", "assets/ai-ml/langchain.svg"),
            ("Apache Spark", "assets/ai-ml/apachespark.svg"),
            ("Docker", "assets/cloud-devops/docker.svg"),
            ("Google Cloud", "assets/cloud-devops/googlecloud.svg"),
        ],
    },
    "devops": {
        "title": "Cloud & DevOps / SRE",
        "subtitle": "Infrastructure as Code • Cloud Orchestration • Observability & Reliability",
        "icons": [
            ("Kubernetes", "assets/cloud-devops/kubernetes.svg"),
            ("Docker", "assets/cloud-devops/docker.svg"),
            ("Terraform", "assets/cloud-devops/terraform.svg"),
            ("AWS", "assets/cloud-devops/aws.svg"),
            ("Prometheus", "assets/cloud-devops/prometheus.svg"),
            ("Grafana", "assets/cloud-devops/grafana.svg"),
            ("Linux", "assets/cloud-devops/linux.svg"),
        ],
    },
    "mobile": {
        "title": "Mobile Software Engineer",
        "subtitle": "iOS & Android Native • Cross-Platform Systems • High-Performance Apps",
        "icons": [
            ("Swift", "assets/mobile/swift.svg"),
            ("Kotlin", "assets/mobile/kotlin.svg"),
            ("Flutter", "assets/mobile/flutter.svg"),
            ("React Native", "assets/mobile/reactnative.svg"),
            ("Expo", "assets/mobile/expo.svg"),
            ("Xcode", "assets/mobile/xcode.svg"),
            ("Android Studio", "assets/mobile/androidstudio.svg"),
        ],
    },
    "data_analyst": {
        "title": "Data Analyst",
        "subtitle": "SQL Analytics • Business Intelligence • Metrics & Statistical Modeling",
        "icons": [
            ("SQL", "assets/databases/postgresql.svg"),
            ("Python", "assets/backend/python.svg"),
            ("Pandas", "assets/ai-ml/pandas.svg"),
            ("Snowflake", "assets/databases/snowflake.svg"),
            ("BigQuery", "assets/databases/bigquery.svg"),
            ("dbt", "assets/databases/dbt.svg"),
            ("Tableau", "assets/ai-ml/tableau.svg"),
            ("Power BI", "assets/ai-ml/powerbi.svg"),
        ],
    },
    "data_scientist": {
        "title": "Data Scientist",
        "subtitle": "Statistical Inference • Predictive Modeling • Machine Learning & Analytics",
        "icons": [
            ("Python", "assets/backend/python.svg"),
            ("R", "assets/ai-ml/r.svg"),
            ("Pandas", "assets/ai-ml/pandas.svg"),
            ("Scikit-Learn", "assets/ai-ml/scikitlearn.svg"),
            ("PyTorch", "assets/ai-ml/pytorch.svg"),
            ("SQL", "assets/databases/postgresql.svg"),
            ("Spark", "assets/ai-ml/apachespark.svg"),
            ("Snowflake", "assets/databases/snowflake.svg"),
        ],
    },
    "data_engineer": {
        "title": "Data Engineer",
        "subtitle": "Distributed Pipelines • Batch & Streaming ETL • Warehousing Architecture",
        "icons": [
            ("Python", "assets/backend/python.svg"),
            ("Spark", "assets/ai-ml/apachespark.svg"),
            ("Kafka", "assets/messaging/kafka.svg"),
            ("Airflow", "assets/ai-ml/airflow.svg"),
            ("Snowflake", "assets/databases/snowflake.svg"),
            ("BigQuery", "assets/databases/bigquery.svg"),
            ("dbt", "assets/databases/dbt.svg"),
            ("Docker", "assets/cloud-devops/docker.svg"),
        ],
    },
    "ai_engineer": {
        "title": "AI Engineer",
        "subtitle": "Foundation Models • LLM Systems & RAG • Multi-Agent Autonomous Workflows",
        "icons": [
            ("Python", "assets/backend/python.svg"),
            ("LangChain", "assets/ai-ml/langchain.svg"),
            ("LangGraph", "assets/ai-ml/langgraph.svg"),
            ("OpenAI", "assets/ai-ml/openai.svg"),
            ("Hugging Face", "assets/ai-ml/huggingface.svg"),
            ("Ollama", "assets/ai-ml/ollama.svg"),
            ("PyTorch", "assets/ai-ml/pytorch.svg"),
            ("Docker", "assets/cloud-devops/docker.svg"),
        ],
    },
    "ml_engineer": {
        "title": "Machine Learning Engineer",
        "subtitle": "Deep Neural Networks • Distributed Training • High-Performance Inference",
        "icons": [
            ("Python", "assets/backend/python.svg"),
            ("PyTorch", "assets/ai-ml/pytorch.svg"),
            ("TensorFlow", "assets/ai-ml/tensorflow.svg"),
            ("JAX", "assets/ai-ml/jax.svg"),
            ("Hugging Face", "assets/ai-ml/huggingface.svg"),
            ("NVIDIA", "assets/ai-ml/nvidia.svg"),
            ("C++", "assets/backend/cplusplus.svg"),
            ("Docker", "assets/cloud-devops/docker.svg"),
        ],
    },
    "mlops_engineer": {
        "title": "MLOps Engineer",
        "subtitle": "Model Deployment & Serving • CI/CD Pipelines • Observability & Governance",
        "icons": [
            ("Python", "assets/backend/python.svg"),
            ("Docker", "assets/cloud-devops/docker.svg"),
            ("Kubernetes", "assets/cloud-devops/kubernetes.svg"),
            ("MLflow", "assets/ai-ml/mlflow.svg"),
            ("Airflow", "assets/ai-ml/airflow.svg"),
            ("W&B", "assets/ai-ml/wandb.svg"),
            ("Terraform", "assets/cloud-devops/terraform.svg"),
            ("Prometheus", "assets/cloud-devops/prometheus.svg"),
        ],
    },
}
